version: "3"
services:
    db:
        container_name: localhost
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: Prathm@1387
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"