FROM python
WORKDIR /Day1/demo/Infobell-Openshift-Daily-Work/16112022/docker/python
COPY main.py /Day1/demo/Infobell-Openshift-Daily-Work/16112022/docker/python
CMD ["python","/Day1/demo/Infobell-Openshift-Daily-Work/16112022/docker/python/main.py"]

