version: "4"
services:
    localhost:
        #container_name: mydb
        image: postgres
        ports:
            - 5432:5432
        restart: always
        environment:   
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: POSTGRES
          POSTGRES_DB: redbus
        volumes:
            - ./localhost:/docker-entrypoint-initdb.d/
        
    app:
        #container_name: myapp
        depends_on:
            - localhost
        restart: always
        build: ./
        ports: 
          - "8000:8000"