version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysqlcontainer
  mysqlcontainer:
    image: "mysql:8"
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_DATABASE: datadb
      MYSQL_ROOT_PASSWORD: cdac

