FROM python

WORKDIR \Users\Malkeet\Work\infobell\Infobell-Openshift-Daily-Work\Docker\.

ADD add.py \Users\Malkeet\Work\infobell\Infobell-Openshift-Daily-Work\Docker 

CMD [ "python" , "C:\Users\Malkeet\Work\infobell\Infobell-Openshift-Daily-Work\Docker\add.py"]
