version: "4"
services:
    localhost:
        #container_name: mydb
        image: postgres
        ports:
            - 5432:5432
        restart: always
        environment:   
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgress
          POSTGRES_DB: restaurants
        
    app:
        #container_name: myapp
        depends_on:
            - localhost
        restart: always
        build: ./
        ports:
            - "8501:8500"

# version: "4"
# services:
#     app:
#         build : ./Dockerfile
#         ports:
#             -'8501:8501'
#         enviroment:
#             POSTGRES_USER = 'postgres'
#             POSTGRES_PASSWORD = 'postgress'
#         restart : always
#     db:
#         image: postgres
#         ports:
#             -'5432:5432'
#         enviroment:
#             POSTGRES_USER = 'postgres'
#             POSTGRES_PASSWORD = 'postgress'
#         restart : always
