version: '3.8'

services:
 image1:
  build:
    context: .
  ports:
  - 8000:5000
  volumes:
  - ./:/app

 mysqldb:
  image: mysql
  ports:
  - 3307:3306
  environment:
  - MYSQL_ROOT_PASSWORD=Chetan@1997
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: