version: '1'
services:
 Spring-bootapp:
   #container name: 
   image: springboot-app
   links:
    - mysqldb
   restart: always
   build: .
   ports:
    - 8243-8250:8243
   environment:
     MYSQL_HOST: mysqldb
     MYSQL USER: root
     MYSQL_PASSWORD: root
     MYSQL_PORT: 3309
     SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3308/test?autoReconnect=true&useSSL=false
   
    

 mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:5.7
    ports:
    - 3308:3308
    environment:
     MYSQL_DATABASE: test
     MYSQL_ROOT_PASSWORD: root

     







 